import { CyberdogShell, Eyebrow } from "@/components/CyberdogShell";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { Bot, ShieldCheck, Sparkles } from "lucide-react";
import { useState } from "react";
import { Streamdown } from "streamdown";
import { toast } from "sonner";
export default function Assist(){const{isAuthenticated}=useAuth();const[prompt,setPrompt]=useState("");const[result,setResult]=useState("");const brief=trpc.ai.creativeBrief.useMutation({onSuccess:data=>setResult(data.content),onError:error=>toast.error(error.message)});return <CyberdogShell><section className="container grid gap-10 py-16 lg:grid-cols-[.85fr_1.15fr]"><div><Eyebrow>Cyberdog Assist / Opt-in AI</Eyebrow><h1 className="font-display text-5xl font-extrabold leading-[.9] tracking-[-.075em]">A clearer first <span className="text-[#e52c2c]">move.</span></h1><p className="mt-6 text-lg leading-8 text-zinc-600">Turn a rough creative problem into a useful first brief. You review every word before it goes anywhere.</p><div className="mt-9 space-y-4"><AssistBoundary icon={ShieldCheck} title="Explicit use" body="Cyberdog Assist is a deliberate tool—not an invisible feature. It uses only the prompt you submit here."/><AssistBoundary icon={ShieldCheck} title="Private message boundary" body="Encrypted private messages are not available to this feature and are never sent for AI processing."/></div></div><div className="rounded-[1.75rem] border border-zinc-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><span className="spectrum-orbit"><Bot className="size-4"/></span><div><h2 className="text-sm font-extrabold">Creative brief desk</h2><p className="text-xs text-zinc-500">Powered by a server-side model; verify output before use.</p></div></div><textarea value={prompt} onChange={event=>setPrompt(event.target.value)} placeholder="Describe the project, audience, tension, and what a useful outcome needs to achieve…" className="mt-6 min-h-44 w-full resize-y rounded-xl border border-zinc-200 bg-[#fbfaf8] p-4 text-sm leading-6 outline-none focus:border-[#e52c2c]"/><div className="mt-3 flex items-center justify-between"><p className="text-xs text-zinc-400">{prompt.length}/2200</p><button disabled={!isAuthenticated||prompt.trim().length<12||brief.isPending} onClick={()=>brief.mutate({prompt})} className="inline-flex items-center gap-2 rounded-lg bg-zinc-950 px-4 py-2.5 text-sm font-extrabold text-white disabled:opacity-50"><Sparkles className="size-4 text-red-300"/>{brief.isPending?"Thinking…":"Draft a brief"}</button></div>{!isAuthenticated&&<p className="mt-3 text-xs font-bold text-[#d22727]">Sign in and explicitly enable Cyberdog Assist in your account to use this feature.</p>}{result&&<div className="prose prose-zinc mt-7 max-w-none rounded-xl border border-zinc-200 bg-[#fbfaf8] p-5 prose-headings:font-display prose-headings:tracking-[-.04em]"><Streamdown>{result}</Streamdown></div>}</div></section></CyberdogShell>}
function AssistBoundary({icon:Icon,title,body}:{icon:any,title:string,body:string}){return <div className="flex gap-3"><span className="grid size-8 shrink-0 place-items-center rounded-lg bg-red-50 text-[#d52929]"><Icon className="size-4"/></span><div><h2 className="text-sm font-extrabold">{title}</h2><p className="mt-1 text-sm leading-6 text-zinc-600">{body}</p></div></div>}
