import { CyberdogShell, Eyebrow } from "@/components/CyberdogShell";
import { startLogin } from "@/const";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { Heart, MessageCircle, Send, ShieldCheck, Sparkles, UserPlus } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

export default function Feed() {
  const { isAuthenticated } = useAuth();
  const [draft, setDraft] = useState("");
  const { data: feed = [], refetch } = trpc.social.feed.useQuery(undefined, { refetchInterval: 20_000 });
  const publish = trpc.social.createPost.useMutation({ onSuccess: () => { setDraft(""); refetch(); toast.success("Your dispatch is live."); }, onError: error => toast.error(error.message) });
  const react = trpc.social.react.useMutation({ onSuccess: () => refetch(), onError: error => toast.error(error.message) });
  return <CyberdogShell><section className="container grid gap-9 py-12 lg:grid-cols-[minmax(0,1fr)_290px]"><div className="max-w-2xl"><Eyebrow>social.cyberdog.io / Community signal</Eyebrow><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h1 className="font-display text-5xl font-extrabold tracking-[-.07em] sm:text-6xl">The signal feed.</h1><p className="mt-4 max-w-xl text-base leading-7 text-zinc-600">Share the in-progress thought, the useful link, or the question that makes the next project smarter.</p></div><span className="inline-flex w-fit items-center gap-2 rounded-full bg-red-50 px-3 py-1.5 text-xs font-bold text-[#cc2828]"><Sparkles className="size-3.5" /> Community dispatches</span></div>
    <div className="mt-9 rounded-2xl border border-zinc-200 bg-white p-5 shadow-sm"><div className="flex gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-full bg-zinc-950 text-sm font-extrabold text-white">{isAuthenticated ? "Y" : "?"}</span><div className="flex-1"><textarea value={draft} onChange={e=>setDraft(e.target.value)} maxLength={4000} placeholder={isAuthenticated ? "What is worth sharing with the pack?" : "Sign in to publish a dispatch"} disabled={!isAuthenticated} className="min-h-24 w-full resize-none rounded-xl border border-zinc-200 bg-[#fbfaf8] p-3 text-sm outline-none transition focus:border-[#e52c2c] focus:ring-2 focus:ring-red-100 disabled:cursor-not-allowed disabled:bg-zinc-100"/><div className="mt-3 flex items-center justify-between"><span className="text-xs text-zinc-400">{draft.length}/4000 · Public by default</span>{isAuthenticated ? <button disabled={!draft.trim()||publish.isPending} onClick={()=>publish.mutate({body:draft,visibility:"public"})} className="inline-flex items-center gap-2 rounded-lg bg-[#e52c2c] px-4 py-2 text-sm font-extrabold text-white disabled:opacity-50"><Send className="size-3.5" /> Publish</button> : <button onClick={()=>startLogin()} className="rounded-lg bg-zinc-950 px-4 py-2 text-sm font-extrabold text-white">Sign in to post</button>}</div></div></div></div>
    <div className="mt-5 space-y-4">{feed.length ? feed.map((item:any)=><article key={item.post.id} className="rounded-2xl border border-zinc-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-full bg-[#e52c2c] text-sm font-extrabold text-white">{(item.authorName||"M").slice(0,1)}</span><div><p className="text-sm font-extrabold">{item.authorName || "Cyberdog member"}</p><p className="text-xs text-zinc-400">Public dispatch · {new Date(item.post.createdAt).toLocaleDateString()}</p></div></div><p className="mt-4 whitespace-pre-wrap text-sm leading-6 text-zinc-700">{item.post.body}</p><div className="mt-5 flex items-center gap-2"><button onClick={()=>isAuthenticated?react.mutate({postId:item.post.id,reaction:"appreciate"}):startLogin()} className="inline-flex items-center gap-1.5 rounded-lg px-2.5 py-1.5 text-xs font-bold text-zinc-500 hover:bg-red-50 hover:text-[#cf2929]"><Heart className="size-3.5" /> Appreciate</button><button onClick={()=>toast.message("Discussion replies will open in the connected community forum.")} className="inline-flex items-center gap-1.5 rounded-lg px-2.5 py-1.5 text-xs font-bold text-zinc-500 hover:bg-zinc-100"><MessageCircle className="size-3.5" /> Discuss</button></div></article>):<EmptyFeed />}</div>
  </div><aside className="space-y-4"><div className="rounded-2xl bg-zinc-950 p-5 text-white"><UserPlus className="size-5 text-red-400"/><h2 className="mt-4 font-display text-2xl font-extrabold tracking-[-.04em]">Follow the good work.</h2><p className="mt-2 text-sm leading-6 text-zinc-400">Your account can follow people, send friend requests, and control how connection requests reach you.</p><a href="/account#connections" className="mt-5 inline-block text-sm font-extrabold text-red-300">Manage connections →</a></div><div className="rounded-2xl border border-zinc-200 bg-white p-5"><ShieldCheck className="size-5 text-[#e52c2c]"/><h2 className="mt-3 text-sm font-extrabold">Good boundaries, clear controls.</h2><p className="mt-2 text-sm leading-6 text-zinc-600">Feed visibility, direct messages, and AI assistance are managed through your unified Cyberdog Account.</p></div></aside></section></CyberdogShell>;
}
function EmptyFeed(){return <div className="rounded-2xl border border-dashed border-zinc-300 bg-white p-10 text-center"><Sparkles className="mx-auto size-6 text-[#e52c2c]"/><h2 className="mt-4 font-display text-2xl font-extrabold">The feed is ready.</h2><p className="mx-auto mt-2 max-w-sm text-sm leading-6 text-zinc-600">Community dispatches will appear here as members begin sharing useful work and clear questions.</p></div>}
