import { CyberdogShell, Eyebrow } from "@/components/CyberdogShell";
import { trpc } from "@/lib/trpc";
import { ArrowUpRight, BookOpenText, CircleHelp, LifeBuoy, MessageSquareText, TicketCheck } from "lucide-react";
import { Link } from "wouter";
import { useEffect, useState } from "react";

export default function Support(){
  const { data } = trpc.support.config.useQuery();
  const [open,setOpen] = useState(false);
  const formUrl = data?.ticketFormUrl || "https://form.jotform.com/262251105333040";
  useEffect(()=>{if(!open)return;const close=(event:KeyboardEvent)=>{if(event.key==="Escape")setOpen(false)};window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close)},[open]);
  return <CyberdogShell><section className="border-b border-zinc-200 bg-white"><div className="container py-16"><Eyebrow>support.cyberdog.io / Help desk</Eyebrow><h1 className="font-display text-5xl font-extrabold tracking-[-.075em] sm:text-7xl">Let’s get you <span className="text-[#e52c2c]">unstuck.</span></h1><p className="mt-5 max-w-2xl text-lg leading-8 text-zinc-600">Use the help desk for account, community, docs, form, or message-envelope issues. The hosted ticket form keeps issue intake structured and traceable.</p></div></section><section className="container grid gap-5 py-12 md:grid-cols-3"><SupportCard icon={TicketCheck} title="Open a ticket" body="Share the affected area, urgency, browser context, and what you have already tried." action="Open help desk form" onClick={()=>setOpen(true)}/><SupportCard icon={BookOpenText} title="Read the docs" body="Account, private-message, and hosted-community guidance is organized in one reliable place." action="Browse docs" href="/docs"/><SupportCard icon={MessageSquareText} title="Community questions" body="For product conversations and ideas others can learn from, take it to the community forum." action="Visit community" href="/community"/></section><section className="container pb-16"><div className="rounded-2xl bg-zinc-950 p-7 text-white sm:p-9"><div className="grid gap-6 md:grid-cols-[auto_1fr_auto]"><span className="grid size-12 place-items-center rounded-xl bg-[#e52c2c]"><LifeBuoy className="size-6"/></span><div><h2 className="font-display text-3xl font-extrabold tracking-[-.05em]">Ticket workflow, without the mystery.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-zinc-400">The hosted support form captures the details needed to categorize and follow up. Authoritative submission records remain in the managed form workspace until a production API/webhook integration is configured.</p></div><CircleHelp className="hidden size-7 text-red-400 md:block"/></div></div></section>{open&&<section role="dialog" aria-modal="true" aria-labelledby="support-form-title" className="fixed inset-0 z-50 grid items-end bg-zinc-950/75 p-0 sm:place-items-center sm:p-4"><div className="flex h-[92vh] w-full max-w-3xl flex-col overflow-hidden rounded-t-2xl bg-white shadow-2xl sm:h-[90vh] sm:rounded-2xl"><div className="flex items-center justify-between border-b border-zinc-200 px-5 py-4"><div><p id="support-form-title" className="text-sm font-extrabold">Cyberdog Creative help desk</p><p className="text-xs text-zinc-500">Managed hosted form</p></div><button autoFocus onClick={()=>setOpen(false)} className="min-h-10 rounded-lg border border-zinc-200 px-3 py-1.5 text-sm font-bold">Close</button></div><iframe title="Cyberdog Creative help desk form" src={formUrl} className="h-full w-full"/></div></section>}</CyberdogShell>
}

function SupportCard({icon:Icon,title,body,action,href,onClick}:{icon:any,title:string,body:string,action:string,href?:string,onClick?:()=>void}){const className="group rounded-2xl border border-zinc-200 bg-white p-6 text-left shadow-sm transition hover:-translate-y-0.5 hover:border-[#e52c2c]";const contents=<><Icon className="size-6 text-[#e52c2c]"/><h2 className="mt-5 font-display text-2xl font-extrabold tracking-[-.04em]">{title}</h2><p className="mt-3 text-sm leading-6 text-zinc-600">{body}</p><span className="mt-7 inline-flex items-center gap-1 text-sm font-extrabold text-[#d42626]">{action}<ArrowUpRight className="size-4 transition group-hover:translate-x-0.5 group-hover:-translate-y-0.5"/></span></>;return onClick?<button onClick={onClick} className={className}>{contents}</button>:<Link href={href||"/"} className={className}>{contents}</Link>}
