import { ArrowLink, CyberdogShell, Eyebrow } from "@/components/CyberdogShell";
import { useBootstrap } from "@/contexts/BootstrapContext";
import { ArrowUpRight, CheckCircle2, LayoutTemplate, X } from "lucide-react";
import { useEffect, useState } from "react";

const examples = [
  { title:"Signal Cabinet", summary:"A coherent system for visual and verbal product expression.", kind:"Identity system", challenge:"A growing product had strong ideas but inconsistent visual language across launch, documentation, and community touchpoints.", approach:["Built a flexible visual vocabulary", "Defined practical editorial principles", "Created reusable launch patterns"], outcome:"A more legible expression system ready for ongoing iteration." },
  { title:"Lighthouse Relay", summary:"A developer launch narrative made legible through docs and patterns.", kind:"Product story", challenge:"A technical release needed to reach developers without flattening the underlying complexity.", approach:["Mapped the release story to real developer questions", "Structured docs around first-use tasks", "Created a layered launch sequence"], outcome:"A launch narrative that supports both discovery and deeper evaluation." },
  { title:"Common Ground", summary:"A community strategy built around meaningful contribution.", kind:"Community design", challenge:"The team needed a community space that rewarded useful participation rather than empty activity.", approach:["Defined contribution patterns", "Designed an intentional category structure", "Made moderation guidance clear"], outcome:"A community model with room for expertise, peer support, and durable knowledge." },
  { title:"Civic Type", summary:"Practical editorial direction for a complex, public-facing product.", kind:"Editorial", challenge:"A public-facing service needed to communicate complex workflows with more confidence and less friction.", approach:["Simplified content hierarchy", "Designed clear response patterns", "Created a durable editorial playbook"], outcome:"A system that helps teams explain difficult work in plain language." },
];

export default function Work(){
  const { portfolio } = useBootstrap();
  const items = portfolio.length ? portfolio.map((item:any) => ({ ...item, kind:item.kind||"Case file", challenge:item.challenge||"A complex creative problem needed a more usable system.", approach:item.approach||["Clarified the real problem", "Built a usable pattern", "Prepared the next handoff"], outcome:item.outcome||"A clearer foundation for the team’s next move." })) : examples;
  const [selected, setSelected] = useState<any | null>(null);
  useEffect(()=>{if(!selected)return;const close=(event:KeyboardEvent)=>{if(event.key==="Escape")setSelected(null)};window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close)},[selected]);
  return <CyberdogShell><section className="container py-12 sm:py-16 lg:py-24"><Eyebrow>Selected work / Case files</Eyebrow><h1 className="max-w-3xl font-display text-5xl font-extrabold leading-[.9] tracking-[-.075em] sm:text-7xl">Useful is a <span className="text-[#e52c2c]">creative</span> advantage.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-zinc-600">Cyberdog Creative helps teams turn complicated ideas into clear products, credible stories, and communities people want to return to.</p><div className="mt-12 grid gap-4 md:mt-14 md:grid-cols-2">{items.map((item:any,index:number)=><article key={item.id??item.title} className="group relative flex min-h-[310px] flex-col overflow-hidden rounded-2xl border border-zinc-200 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><div className={`absolute inset-x-0 top-0 h-2 ${index%3===1?'bg-zinc-950':'bg-[#e52c2c]'}`} />{item.imageUrl&&<img src={item.imageUrl} alt={`${item.title} project cover`} className="h-44 w-full object-cover"/>}<div className="flex flex-1 flex-col p-6 sm:p-7"><div className="grid size-11 place-items-center rounded-xl bg-[#f5f3ef] text-[#e52c2c]"><LayoutTemplate className="size-5" /></div><p className="mt-7 text-[10px] font-extrabold uppercase tracking-[.16em] text-zinc-400">{item.kind}</p><h2 className="mt-3 font-display text-3xl font-extrabold tracking-[-.055em]">{item.title}</h2><p className="mt-4 max-w-md text-sm leading-6 text-zinc-600">{item.summary}</p><button onClick={()=>setSelected(item)} className="mt-auto inline-flex min-h-11 w-fit items-center gap-2 pt-6 text-sm font-extrabold text-[#ce2525]" aria-label={`Read the ${item.title} case study`}>Read case file <ArrowUpRight className="size-4" /></button></div></article>)}</div><div className="mt-10 flex flex-col gap-3 rounded-xl border border-dashed border-zinc-300 bg-white p-5 text-sm text-zinc-600 sm:mt-12 sm:flex-row sm:items-center sm:gap-2"><span className="font-bold text-zinc-950">Want this kind of clarity?</span><ArrowLink href="/contact">Start a project conversation</ArrowLink></div></section>{selected&&<CaseStudy caseStudy={selected} onClose={()=>setSelected(null)}/>}</CyberdogShell>}

function CaseStudy({caseStudy,onClose}:{caseStudy:any,onClose:()=>void}){return <section role="dialog" aria-modal="true" aria-labelledby="case-study-title" className="fixed inset-0 z-50 grid items-end bg-zinc-950/75 p-0 sm:place-items-center sm:p-6"><div className="max-h-[92vh] w-full max-w-3xl overflow-y-auto rounded-t-2xl bg-white p-6 shadow-2xl sm:rounded-2xl sm:p-8"><div className="flex items-start justify-between gap-5"><div><p className="text-[10px] font-extrabold uppercase tracking-[.16em] text-[#d22828]">{caseStudy.kind}</p><h2 id="case-study-title" className="mt-3 font-display text-4xl font-extrabold tracking-[-.06em] sm:text-5xl">{caseStudy.title}</h2></div><button autoFocus onClick={onClose} className="grid size-11 shrink-0 place-items-center rounded-lg border border-zinc-200 text-zinc-600 hover:border-[#e52c2c] hover:text-[#e52c2c]" aria-label="Close case study"><X className="size-5" /></button></div>{caseStudy.imageUrl&&<img src={caseStudy.imageUrl} alt={`${caseStudy.title} project cover`} className="mt-6 max-h-80 w-full rounded-xl object-cover"/>}<p className="mt-5 text-base leading-7 text-zinc-600">{caseStudy.summary}</p><div className="mt-8 grid gap-6 border-y border-zinc-200 py-7 sm:grid-cols-2"><div><h3 className="text-sm font-extrabold">The situation</h3><p className="mt-3 text-sm leading-6 text-zinc-600">{caseStudy.challenge}</p></div><div><h3 className="text-sm font-extrabold">The outcome</h3><p className="mt-3 text-sm leading-6 text-zinc-600">{caseStudy.outcome}</p></div></div><div className="mt-7"><h3 className="text-sm font-extrabold">How the work moved</h3><ul className="mt-4 grid gap-3 sm:grid-cols-3">{caseStudy.approach.map((step:string)=> <li key={step} className="rounded-xl bg-[#f7f5f1] p-4 text-sm leading-5 text-zinc-700"><CheckCircle2 className="mb-3 size-4 text-[#e52c2c]"/>{step}</li>)}</ul></div><div className="mt-8 flex flex-col gap-3 border-t border-zinc-200 pt-6 sm:flex-row sm:items-center sm:justify-between"><p className="text-sm text-zinc-600">Discuss a similar challenge with Cyberdog Creative.</p><ArrowLink href="/contact">Open project inquiry</ArrowLink></div></div></section>}
